"""Embedding identity and bank compatibility guards.

Embeddings are only useful for nearest-neighbour search when the vectors in a
bank and the vectors generated by the running process share the same semantic
space.  A dimension check is insufficient (many unrelated models produce the
same number of coordinates), so banks persist a small, redacted fingerprint.

The module deliberately has no dependency on a particular embedding SDK.  It
uses the public attributes exposed by :class:`~hms_api.engine.embeddings.Embeddings`
and tolerates light-weight test doubles as well.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
from collections.abc import Mapping
from typing import Any
from urllib.parse import urlsplit, urlunsplit

from .schema import fq_table

logger = logging.getLogger(__name__)

FINGERPRINT_SCHEMA_VERSION = 1
# ``augment_texts_with_dates`` appends a readable date/range and then entity
# names to the text sent to the encoder.  Keep this explicit: changing that
# transformation must create a new bank identity.
EMBEDDING_INPUT_SCHEMA_VERSION = "retain.fact_text+date_range+entities.v1"
FINGERPRINT_POLICIES = frozenset({"strict", "warn", "off"})


class EmbeddingFingerprintError(RuntimeError):
    """Base class for embedding compatibility failures."""


class EmbeddingFingerprintMismatchError(EmbeddingFingerprintError):
    """Raised when a bank was created with a different semantic encoder."""


class EmbeddingFingerprintUnknownError(EmbeddingFingerprintError):
    """Raised when a non-empty legacy bank has no trustworthy fingerprint."""


class EmbeddingFingerprintSchemaError(EmbeddingFingerprintError):
    """Raised when a persisted fingerprint is malformed."""


def _normalise_text(value: Any, *, lower: bool = True) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    return text.lower() if lower else text


def canonical_model_name(value: Any) -> str | None:
    """Return a stable model name without harmless registry aliases.

    BGE models are commonly reported as either ``BAAI/bge-small-en-v1.5`` or
    ``bge-small-en-v1.5`` (especially by OpenAI-compatible TEI proxies).  The
    organisation prefix is not part of the model weights, so strip it for the
    known BGE family.  Other prefixes remain significant because they select a
    different model namespace.
    """

    text = _normalise_text(value)
    if text is None:
        return None
    text = re.sub(r"\s+", " ", text)
    if text.startswith("baai/"):
        text = text[5:]
    return text


def canonical_endpoint(value: Any) -> str | None:
    """Canonicalise an endpoint while removing credentials and query data.

    API keys are often supplied as URL user-info or query parameters (for
    example Azure's ``api-version``).  Neither belongs in a bank fingerprint.
    Only scheme, host/port and path are retained; malformed/non-URL values are
    reduced to a conservative redacted token.
    """

    text = _normalise_text(value, lower=False)
    if text is None:
        return None
    try:
        parsed = urlsplit(text)
        if parsed.scheme and parsed.netloc:
            # ``hostname`` drops user-info and normalises case.  Preserve an
            # explicitly supplied non-default port, but never the password.
            host = parsed.hostname or ""
            host = host.lower()
            try:
                port = parsed.port
            except ValueError:
                port = None
            netloc = host
            if port is not None:
                netloc = f"{netloc}:{port}"
            path_parts = []
            redact_next = False
            for part in parsed.path.split("/"):
                if not part:
                    continue
                lowered = part.lower()
                sensitive = redact_next or lowered.startswith(("sk-", "key-", "token-")) or len(part) > 64
                path_parts.append("_redacted_" if sensitive else part)
                redact_next = lowered in {"key", "api-key", "apikey", "token", "secret"}
            path = "/" + "/".join(path_parts) if path_parts else "/"
            return urlunsplit((parsed.scheme.lower(), netloc, path, "", ""))
    except (TypeError, ValueError):
        pass
    # Do not persist arbitrary strings that could contain a secret.  Keep a
    # short, punctuation-safe marker useful for diagnostics only.
    return "opaque:" + hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def _model_attr(model: Any, *names: str) -> Any:
    for name in names:
        try:
            value = getattr(model, name, None)
        except Exception:
            value = None
        if value is not None and value != "":
            return value
    return None


def _dimension(model: Any) -> int | None:
    value = _model_attr(model, "dimension", "_dimension")
    try:
        return int(value) if value is not None else None
    except (TypeError, ValueError):
        return None


def _semantic_provider(transport_provider: str | None, model: str | None) -> str | None:
    """Infer a model-family provider independently from transport.

    ``litellm`` and TEI are transports, not model families.  When a model name
    carries an explicit registry prefix, use that prefix; this lets a local
    BGE model and a TEI-hosted BGE model attest to the same semantic space.
    """

    if model and model.startswith(("bge-", "bge_")):
        return "model-registry"
    if model and "/" in model:
        prefix = model.split("/", 1)[0]
        if prefix in {"openai", "cohere", "voyage", "vertex_ai", "google", "huggingface", "mistral", "baai"}:
            return "huggingface" if prefix == "baai" else prefix
    if transport_provider in {"local", "tei", "remote-tei", "huggingface"}:
        return "model-registry"
    return transport_provider


def _digest_payload(payload: Mapping[str, Any]) -> str:
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _calibration_digest(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, str) and re.fullmatch(r"[0-9a-fA-F]{64}", value.strip()):
        return value.strip().lower()
    if isinstance(value, bytes):
        raw = value
    else:
        try:
            raw = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
        except (TypeError, ValueError):
            raw = str(value).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def build_embedding_fingerprint(
    embeddings_model: Any,
    *,
    input_schema_version: str = EMBEDDING_INPUT_SCHEMA_VERSION,
    calibration_probe_digest: Any = None,
) -> dict[str, Any]:
    """Build a deterministic, JSON-safe fingerprint for an encoder.

    The returned mapping contains both the complete ``hash`` (including
    transport diagnostics) and ``compatibility_hash`` (semantic identity used
    by guards).  No API key, token, URL query, or service-account material is
    read or persisted.
    """

    transport_provider = _normalise_text(_model_attr(embeddings_model, "provider_name", "provider")) or "unknown"
    model = (
        canonical_model_name(_model_attr(embeddings_model, "model", "model_name", "_model_id", "model_id")) or "unknown"
    )
    dimension = _dimension(embeddings_model)
    output_dimensions = _model_attr(embeddings_model, "output_dimensions", "output_dimensionality", "dimensions")
    try:
        output_dimensions = int(output_dimensions) if output_dimensions is not None else None
    except (TypeError, ValueError):
        output_dimensions = None
    encoding_format = _normalise_text(_model_attr(embeddings_model, "encoding_format"))
    normalization = _model_attr(
        embeddings_model,
        "normalization",
        "normalize_embeddings",
        "normalize",
        "_normalize_embeddings",
    )
    if isinstance(normalization, str):
        normalization = normalization.strip().lower() or None
    elif normalization is not None:
        normalization = bool(normalization)
    input_type = _normalise_text(_model_attr(embeddings_model, "input_type", "task_type"))
    endpoint = canonical_endpoint(_model_attr(embeddings_model, "base_url", "api_base", "endpoint", "url"))
    revision = canonical_model_name(_model_attr(embeddings_model, "revision", "model_revision", "commit_hash"))
    semantic_provider = _semantic_provider(transport_provider, model)
    calibration = _calibration_digest(
        calibration_probe_digest
        if calibration_probe_digest is not None
        else _model_attr(embeddings_model, "calibration_probe_digest")
    )

    # Keep field names explicit and stable.  ``None`` values are retained so a
    # later model initialisation that discovers a dimension cannot silently
    # compare equal to an uninitialised encoder.
    payload: dict[str, Any] = {
        "schema_version": FINGERPRINT_SCHEMA_VERSION,
        "provider": transport_provider,
        "semantic_provider": semantic_provider,
        "model": model,
        "revision": revision,
        "dimension": dimension,
        "output_dimensions": output_dimensions,
        "encoding_format": encoding_format,
        "normalization": normalization,
        "input_type": input_type,
        "endpoint": endpoint,
        "input_schema": _normalise_text(input_schema_version, lower=False) or EMBEDDING_INPUT_SCHEMA_VERSION,
        "calibration_probe_digest": calibration,
    }
    # Transport-independent identity.  Endpoint and transport provider are
    # intentionally excluded; the model family and preprocessing contract are
    # what determine whether cosine similarity is meaningful.
    compatibility_payload = {
        key: payload[key]
        for key in (
            "schema_version",
            "semantic_provider",
            "model",
            "revision",
            "dimension",
            "output_dimensions",
            "encoding_format",
            "normalization",
            "input_type",
            "input_schema",
            "calibration_probe_digest",
        )
    }
    result = dict(payload)
    result["hash"] = _digest_payload(payload)
    result["compatibility_hash"] = _digest_payload(compatibility_payload)
    return result


def canonical_fingerprint(value: Any) -> dict[str, Any] | None:
    """Parse and canonicalise a value read from JSONB/CLOB.

    Legacy projection/migration rows may contain a JSON string or a plain
    ``model:dimension`` string.  Those values are returned as a tagged legacy
    mapping and are never treated as a trustworthy modern fingerprint without
    explicit attestation.
    """

    if value is None:
        return None
    if isinstance(value, (bytes, bytearray)):
        value = value.decode("utf-8", errors="replace")
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return None
        try:
            value = json.loads(text)
        except json.JSONDecodeError:
            return {"legacy": True, "version": text}
    if not isinstance(value, Mapping):
        raise EmbeddingFingerprintSchemaError("Persisted embedding fingerprint must be a JSON object or legacy string")
    result = {str(k): v for k, v in value.items()}
    if result.get("legacy"):
        result["legacy"] = True
        result["version"] = str(result.get("version") or result.get("value") or "")
        return result
    # Recompute hashes rather than trusting user-editable JSON fields.
    required = ("schema_version", "model", "dimension", "input_schema")
    if any(key not in result for key in required):
        raise EmbeddingFingerprintSchemaError(
            "Persisted embedding fingerprint is missing one of: " + ", ".join(required)
        )
    payload = {
        key: result.get(key)
        for key in (
            "schema_version",
            "provider",
            "semantic_provider",
            "model",
            "revision",
            "dimension",
            "output_dimensions",
            "encoding_format",
            "normalization",
            "input_type",
            "endpoint",
            "input_schema",
            "calibration_probe_digest",
        )
    }
    # Keep a normalized payload even if an older writer omitted optional keys.
    payload["schema_version"] = int(payload["schema_version"])
    payload["model"] = canonical_model_name(payload.get("model")) or "unknown"
    payload["provider"] = _normalise_text(payload.get("provider")) or "unknown"
    payload["semantic_provider"] = _normalise_text(payload.get("semantic_provider")) or _semantic_provider(
        payload["provider"], payload["model"]
    )
    payload["revision"] = canonical_model_name(payload.get("revision"))
    payload["endpoint"] = canonical_endpoint(payload.get("endpoint"))
    payload["input_schema"] = (
        _normalise_text(payload.get("input_schema"), lower=False) or EMBEDDING_INPUT_SCHEMA_VERSION
    )
    try:
        payload["dimension"] = int(payload["dimension"]) if payload["dimension"] is not None else None
        payload["output_dimensions"] = (
            int(payload["output_dimensions"]) if payload["output_dimensions"] is not None else None
        )
    except (TypeError, ValueError) as exc:
        raise EmbeddingFingerprintSchemaError("Persisted embedding fingerprint dimension is invalid") from exc
    payload["encoding_format"] = _normalise_text(payload.get("encoding_format"))
    if isinstance(payload.get("normalization"), str):
        payload["normalization"] = payload["normalization"].strip().lower() or None
    elif payload.get("normalization") is not None:
        payload["normalization"] = bool(payload["normalization"])
    payload["input_type"] = _normalise_text(payload.get("input_type"))
    payload["calibration_probe_digest"] = _calibration_digest(payload.get("calibration_probe_digest"))
    result = payload
    result["hash"] = _digest_payload(payload)
    compatibility_payload = {
        key: payload[key]
        for key in (
            "schema_version",
            "semantic_provider",
            "model",
            "revision",
            "dimension",
            "output_dimensions",
            "encoding_format",
            "normalization",
            "input_type",
            "input_schema",
            "calibration_probe_digest",
        )
    }
    result["compatibility_hash"] = _digest_payload(compatibility_payload)
    return result


def embedding_model_version(embeddings_model: Any) -> str:
    """Return the stable identifier stored in ``projection.embedding.v``."""

    return "fp:" + build_embedding_fingerprint(embeddings_model)["compatibility_hash"]


def fingerprint_matches(stored: Any, current: Mapping[str, Any]) -> bool:
    """Compare semantic identities, ignoring transport-only fields."""

    stored_fp = canonical_fingerprint(stored)
    current_fp = canonical_fingerprint(current)
    if not stored_fp or not current_fp or stored_fp.get("legacy") or current_fp.get("legacy"):
        return False
    return stored_fp.get("compatibility_hash") == current_fp.get("compatibility_hash")


def _policy(policy: str | None) -> str:
    value = (policy or "strict").strip().lower()
    if value not in FINGERPRINT_POLICIES:
        raise ValueError(f"Invalid embedding fingerprint policy {policy!r}; expected strict, warn, or off")
    return value


def _legacy_version_matches(version: str, current: Mapping[str, Any]) -> bool:
    """Match an explicitly supplied legacy ``model:dimension`` identity."""

    model_text, separator, dimension_text = version.strip().rpartition(":")
    if not separator:
        return False
    try:
        dimension = int(dimension_text)
    except ValueError:
        return False
    # Old LiteLLM versions sometimes included a transport prefix.  Strip only
    # known transport prefixes before applying the model alias normalizer.
    lowered = model_text.strip().lower()
    for prefix in ("local/", "tei/", "litellm/", "litellm-sdk/", "openai-compatible/"):
        if lowered.startswith(prefix):
            model_text = model_text[len(prefix) :]
            break
    return canonical_model_name(model_text) == current.get("model") and dimension == current.get("dimension")


def _attestation_matches(attestation: Any, current: Mapping[str, Any], *, legacy_version: str | None = None) -> bool:
    """Validate an explicit legacy attestation against the running encoder."""

    if attestation is None:
        return False
    value = attestation
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return False
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            parsed = None
        if parsed is not None:
            value = parsed
        else:
            accepted = {
                str(current.get("hash")),
                str(current.get("compatibility_hash")),
                "fp:" + str(current.get("compatibility_hash")),
            }
            if text in accepted or _legacy_version_matches(text, current):
                return (
                    legacy_version is None or text == legacy_version or _legacy_version_matches(legacy_version, current)
                )
            return False
    if isinstance(value, Mapping):
        expected_legacy = value.get("legacy_version")
        if legacy_version is not None and expected_legacy is not None and str(expected_legacy) != legacy_version:
            return False
        nested = value.get("fingerprint") or value.get("current_fingerprint")
        if nested is not None:
            try:
                return fingerprint_matches(nested, current)
            except EmbeddingFingerprintSchemaError:
                return False
        compatibility_hash = value.get("compatibility_hash")
        if compatibility_hash is not None:
            return str(compatibility_hash) == current.get("compatibility_hash")
        full_hash = value.get("hash")
        if full_hash is not None and len(value) <= 3:
            return str(full_hash) == current.get("hash")
        try:
            return fingerprint_matches(value, current)
        except EmbeddingFingerprintSchemaError:
            return False
    return False


def _row_value(row: Any, key: str) -> Any:
    if row is None:
        return None
    try:
        return row[key]
    except (KeyError, TypeError, IndexError):
        return getattr(row, key, None)


async def _bank_state(conn: Any, bank_id: str, *, lock: bool = False) -> tuple[Any, bool | None]:
    suffix = " FOR UPDATE" if lock else ""
    row = await conn.fetchrow(
        f"SELECT embedding_fingerprint FROM {fq_table('banks')} WHERE bank_id = $1{suffix}",
        bank_id,
    )
    if row is None:
        return None, None
    fingerprint = _row_value(row, "embedding_fingerprint")
    # A bank with no stored vectors is allowed to establish its identity even
    # when it contains lexical-only units from a previous embedding outage.
    # Use a cheap EXISTS query rather than COUNT so this remains bounded.
    if getattr(conn, "backend_type", "postgresql") == "oracle":
        nonempty = await conn.fetchval(
            f"SELECT CASE WHEN EXISTS ("
            f"SELECT 1 FROM {fq_table('memory_units')} WHERE bank_id = $1 AND embedding IS NOT NULL"
            ") THEN 1 ELSE 0 END FROM DUAL",
            bank_id,
        )
    else:
        nonempty = await conn.fetchval(
            f"SELECT EXISTS (SELECT 1 FROM {fq_table('memory_units')} WHERE bank_id = $1 AND embedding IS NOT NULL)",
            bank_id,
        )
    return fingerprint, bool(nonempty)


async def _persist_fingerprint(conn: Any, bank_id: str, fingerprint: Mapping[str, Any]) -> None:
    serialized = json.dumps(fingerprint, sort_keys=True, separators=(",", ":"))
    backend_type = getattr(conn, "backend_type", "postgresql")
    if backend_type == "postgresql":
        await conn.execute(
            f"UPDATE {fq_table('banks')} SET embedding_fingerprint = $2::jsonb WHERE bank_id = $1",
            bank_id,
            serialized,
        )
    else:
        await conn.execute(
            f"UPDATE {fq_table('banks')} SET embedding_fingerprint = $2 WHERE bank_id = $1",
            bank_id,
            serialized,
        )


async def validate_bank_embedding_fingerprint(
    conn: Any,
    bank_id: str,
    current: Mapping[str, Any],
    *,
    policy: str = "strict",
    for_write: bool = False,
    legacy_attestation: Any = None,
) -> dict[str, Any]:
    """Validate a bank fingerprint, optionally initialising an empty bank.

    ``for_write=True`` acquires a row lock and conditionally initialises a NULL
    fingerprint in the same transaction as the caller's first fact write.
    Legacy rows are never inferred from projection ``v=1``.  Callers that have
    independently calibrated a legacy bank may pass its exact legacy version
    via ``legacy_attestation``.
    """

    policy_value = _policy(policy)
    current_fp = canonical_fingerprint(current)
    if current_fp is None or current_fp.get("legacy"):
        raise EmbeddingFingerprintSchemaError("Current embedding fingerprint is not a modern JSON object")
    if policy_value == "off":
        return current_fp

    stored_raw, nonempty = await _bank_state(conn, bank_id, lock=for_write)
    if stored_raw is None and nonempty is None:
        # Read paths should preserve their historical behaviour for a bank that
        # does not exist; retain's get_or_create path normally makes this
        # impossible, but a clear error is safer inside a write transaction.
        if for_write:
            raise EmbeddingFingerprintError(f"Cannot fingerprint unknown bank {bank_id!r}: bank row does not exist")
        return current_fp

    stored_fp = canonical_fingerprint(stored_raw) if stored_raw is not None else None
    if stored_fp and stored_fp.get("legacy"):
        if _attestation_matches(
            legacy_attestation,
            current_fp,
            legacy_version=str(stored_fp.get("version") or ""),
        ):
            logger.warning("Using explicitly attested legacy embedding fingerprint for bank %s", bank_id)
            if for_write:
                await _persist_fingerprint(conn, bank_id, current_fp)
            return current_fp
        message = (
            f"Bank {bank_id!r} has a legacy embedding fingerprint ({stored_fp.get('version')!r}); "
            "projection metadata cannot establish vector compatibility. "
            "Re-index the bank or provide an explicit legacy attestation."
        )
        if policy_value == "warn":
            logger.warning(message)
            return current_fp
        raise EmbeddingFingerprintUnknownError(message)

    if stored_fp is None:
        if not nonempty:
            if for_write:
                await _persist_fingerprint(conn, bank_id, current_fp)
                return current_fp
            # A read against an empty bank need not mutate it.
            return current_fp
        if _attestation_matches(legacy_attestation, current_fp):
            logger.warning("Using explicit embedding attestation for legacy bank %s", bank_id)
            if for_write:
                await _persist_fingerprint(conn, bank_id, current_fp)
            return current_fp
        message = (
            f"Bank {bank_id!r} contains memory units but has no embedding fingerprint. "
            "Refusing to compare vectors without an explicit legacy attestation."
        )
        if policy_value == "warn":
            logger.warning(message)
            return current_fp
        raise EmbeddingFingerprintUnknownError(message)

    if fingerprint_matches(stored_fp, current_fp):
        return current_fp

    # Once every vector has been removed, no incompatible coordinates remain.
    # A new write may therefore establish a new space under the same row lock.
    if not nonempty:
        if for_write:
            await _persist_fingerprint(conn, bank_id, current_fp)
        return current_fp

    message = (
        f"Embedding fingerprint mismatch for bank {bank_id!r}: stored={stored_fp.get('hash', 'unknown')[:16]} "
        f"current={current_fp.get('hash', 'unknown')[:16]}. "
        "Use the encoder that created the bank or explicitly re-index/attest it; "
        "semantic recall and writes must not silently mix vector spaces."
    )
    if policy_value == "warn":
        logger.warning(message)
        return current_fp
    raise EmbeddingFingerprintMismatchError(message)


async def ensure_bank_embedding_fingerprint(
    conn: Any,
    bank_id: str,
    embeddings_model: Any,
    *,
    policy: str = "strict",
    for_write: bool = False,
    legacy_attestation: Any = None,
) -> dict[str, Any]:
    """Convenience wrapper that fingerprints an encoder object and validates it."""

    current = build_embedding_fingerprint(embeddings_model)
    return await validate_bank_embedding_fingerprint(
        conn,
        bank_id,
        current,
        policy=policy,
        for_write=for_write,
        legacy_attestation=legacy_attestation,
    )


__all__ = [
    "EMBEDDING_INPUT_SCHEMA_VERSION",
    "FINGERPRINT_POLICIES",
    "EmbeddingFingerprintError",
    "EmbeddingFingerprintMismatchError",
    "EmbeddingFingerprintSchemaError",
    "EmbeddingFingerprintUnknownError",
    "build_embedding_fingerprint",
    "canonical_endpoint",
    "canonical_fingerprint",
    "canonical_model_name",
    "embedding_model_version",
    "ensure_bank_embedding_fingerprint",
    "fingerprint_matches",
    "validate_bank_embedding_fingerprint",
]
