/*
HMS HTTP API

HTTP API for HMS

API version: 0.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hms

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type MonitoringAPI interface {

	/*
		GetVersion Get API version and feature flags

		Returns API version information and enabled feature flags. Use include_multimodal=true to negotiate the additive multimodal capability fields.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return MonitoringAPIGetVersionRequest
	*/
	GetVersion(ctx context.Context) MonitoringAPIGetVersionRequest

	// GetVersionExecute executes the request
	//  @return VersionResponse
	GetVersionExecute(r MonitoringAPIGetVersionRequest) (*VersionResponse, *http.Response, error)

	/*
		HealthEndpointHealthGet Health check endpoint

		Checks the health of the API and database connection

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return MonitoringAPIHealthEndpointHealthGetRequest
	*/
	HealthEndpointHealthGet(ctx context.Context) MonitoringAPIHealthEndpointHealthGetRequest

	// HealthEndpointHealthGetExecute executes the request
	//  @return interface{}
	HealthEndpointHealthGetExecute(r MonitoringAPIHealthEndpointHealthGetRequest) (interface{}, *http.Response, error)

	/*
		MetricsEndpointMetricsGet Prometheus metrics endpoint

		Exports metrics in Prometheus format for scraping

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return MonitoringAPIMetricsEndpointMetricsGetRequest
	*/
	MetricsEndpointMetricsGet(ctx context.Context) MonitoringAPIMetricsEndpointMetricsGetRequest

	// MetricsEndpointMetricsGetExecute executes the request
	//  @return interface{}
	MetricsEndpointMetricsGetExecute(r MonitoringAPIMetricsEndpointMetricsGetRequest) (interface{}, *http.Response, error)
}

// MonitoringAPIService MonitoringAPI service
type MonitoringAPIService service

// Backward-compatible aliases retained for clients generated before the
// MonitoringAPI interface naming change in OpenAPI Generator 7.10.
type ApiGetVersionRequest = MonitoringAPIGetVersionRequest
type ApiHealthEndpointHealthGetRequest = MonitoringAPIHealthEndpointHealthGetRequest
type ApiMetricsEndpointMetricsGetRequest = MonitoringAPIMetricsEndpointMetricsGetRequest

type MonitoringAPIGetVersionRequest struct {
	ctx               context.Context
	ApiService        MonitoringAPI
	includeMultimodal *bool
}

// Include additive multimodal capability flags. The default preserves the legacy wire shape for strict older SDKs.
func (r MonitoringAPIGetVersionRequest) IncludeMultimodal(includeMultimodal bool) MonitoringAPIGetVersionRequest {
	r.includeMultimodal = &includeMultimodal
	return r
}

func (r MonitoringAPIGetVersionRequest) Execute() (*VersionResponse, *http.Response, error) {
	return r.ApiService.GetVersionExecute(r)
}

/*
GetVersion Get API version and feature flags

Returns API version information and enabled feature flags. Use include_multimodal=true to negotiate the additive multimodal capability fields.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return MonitoringAPIGetVersionRequest
*/
func (a *MonitoringAPIService) GetVersion(ctx context.Context) MonitoringAPIGetVersionRequest {
	return MonitoringAPIGetVersionRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return VersionResponse
func (a *MonitoringAPIService) GetVersionExecute(r MonitoringAPIGetVersionRequest) (*VersionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *VersionResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitoringAPIService.GetVersion")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/version"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.includeMultimodal != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_multimodal", r.includeMultimodal, "form", "")
	} else {
		var defaultValue bool = false
		r.includeMultimodal = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type MonitoringAPIHealthEndpointHealthGetRequest struct {
	ctx        context.Context
	ApiService MonitoringAPI
}

func (r MonitoringAPIHealthEndpointHealthGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.HealthEndpointHealthGetExecute(r)
}

/*
HealthEndpointHealthGet Health check endpoint

Checks the health of the API and database connection

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return MonitoringAPIHealthEndpointHealthGetRequest
*/
func (a *MonitoringAPIService) HealthEndpointHealthGet(ctx context.Context) MonitoringAPIHealthEndpointHealthGetRequest {
	return MonitoringAPIHealthEndpointHealthGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return interface{}
func (a *MonitoringAPIService) HealthEndpointHealthGetExecute(r MonitoringAPIHealthEndpointHealthGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitoringAPIService.HealthEndpointHealthGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/health"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type MonitoringAPIMetricsEndpointMetricsGetRequest struct {
	ctx        context.Context
	ApiService MonitoringAPI
}

func (r MonitoringAPIMetricsEndpointMetricsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.MetricsEndpointMetricsGetExecute(r)
}

/*
MetricsEndpointMetricsGet Prometheus metrics endpoint

Exports metrics in Prometheus format for scraping

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return MonitoringAPIMetricsEndpointMetricsGetRequest
*/
func (a *MonitoringAPIService) MetricsEndpointMetricsGet(ctx context.Context) MonitoringAPIMetricsEndpointMetricsGetRequest {
	return MonitoringAPIMetricsEndpointMetricsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return interface{}
func (a *MonitoringAPIService) MetricsEndpointMetricsGetExecute(r MonitoringAPIMetricsEndpointMetricsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MonitoringAPIService.MetricsEndpointMetricsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/metrics"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
