/*
HMS HTTP API

HTTP API for HMS

API version: 0.6.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hms

import (
	"encoding/json"
)

// checks if the MultimodalOperationMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultimodalOperationMetadata{}

// MultimodalOperationMetadata Stable, payload-free status for a multimodal file-retain operation.
type MultimodalOperationMetadata struct {
	AssetId                          NullableString `json:"asset_id,omitempty"`
	AssetSha256                      NullableString `json:"asset_sha256,omitempty" validate:"regexp=^[0-9a-f]{64}$"`
	MediaKind                        NullableString `json:"media_kind,omitempty"`
	PipelineVersion                  NullableString `json:"pipeline_version,omitempty"`
	DescriptorModel                  NullableString `json:"descriptor_model,omitempty"`
	ResolvedModel                    NullableString `json:"resolved_model,omitempty"`
	Stage                            NullableString `json:"stage,omitempty"`
	ChildRetainOperationId           NullableString `json:"child_retain_operation_id,omitempty" validate:"regexp=^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"`
	ChildRetainStatus                NullableString `json:"child_retain_status,omitempty"`
	RecallReady                      NullableBool   `json:"recall_ready,omitempty"`
	Retryable                        NullableBool   `json:"retryable,omitempty"`
	SanitizedErrorCode               NullableString `json:"sanitized_error_code,omitempty" validate:"regexp=^[a-z0-9]+(?:[._-][a-z0-9]+)*$"`
	ProviderRequestId                NullableString `json:"provider_request_id,omitempty"`
	InputTokens                      NullableInt64  `json:"input_tokens,omitempty"`
	OutputTokens                     NullableInt64  `json:"output_tokens,omitempty"`
	LogicalCalls                     NullableInt64  `json:"logical_calls,omitempty"`
	PhysicalAttempts                 NullableInt64  `json:"physical_attempts,omitempty"`
	PossibleDuplicateProviderAttempt NullableBool   `json:"possible_duplicate_provider_attempt,omitempty"`
}

// NewMultimodalOperationMetadata instantiates a new MultimodalOperationMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultimodalOperationMetadata() *MultimodalOperationMetadata {
	this := MultimodalOperationMetadata{}
	return &this
}

// NewMultimodalOperationMetadataWithDefaults instantiates a new MultimodalOperationMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultimodalOperationMetadataWithDefaults() *MultimodalOperationMetadata {
	this := MultimodalOperationMetadata{}
	return &this
}

// GetAssetId returns the AssetId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetAssetId() string {
	if o == nil || IsNil(o.AssetId.Get()) {
		var ret string
		return ret
	}
	return *o.AssetId.Get()
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetId.Get(), o.AssetId.IsSet()
}

// HasAssetId returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasAssetId() bool {
	if o != nil && o.AssetId.IsSet() {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given NullableString and assigns it to the AssetId field.
func (o *MultimodalOperationMetadata) SetAssetId(v string) {
	o.AssetId.Set(&v)
}

// SetAssetIdNil sets the value for AssetId to be an explicit nil
func (o *MultimodalOperationMetadata) SetAssetIdNil() {
	o.AssetId.Set(nil)
}

// UnsetAssetId ensures that no value is present for AssetId, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetAssetId() {
	o.AssetId.Unset()
}

// GetAssetSha256 returns the AssetSha256 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetAssetSha256() string {
	if o == nil || IsNil(o.AssetSha256.Get()) {
		var ret string
		return ret
	}
	return *o.AssetSha256.Get()
}

// GetAssetSha256Ok returns a tuple with the AssetSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetAssetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetSha256.Get(), o.AssetSha256.IsSet()
}

// HasAssetSha256 returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasAssetSha256() bool {
	if o != nil && o.AssetSha256.IsSet() {
		return true
	}

	return false
}

// SetAssetSha256 gets a reference to the given NullableString and assigns it to the AssetSha256 field.
func (o *MultimodalOperationMetadata) SetAssetSha256(v string) {
	o.AssetSha256.Set(&v)
}

// SetAssetSha256Nil sets the value for AssetSha256 to be an explicit nil
func (o *MultimodalOperationMetadata) SetAssetSha256Nil() {
	o.AssetSha256.Set(nil)
}

// UnsetAssetSha256 ensures that no value is present for AssetSha256, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetAssetSha256() {
	o.AssetSha256.Unset()
}

// GetMediaKind returns the MediaKind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetMediaKind() string {
	if o == nil || IsNil(o.MediaKind.Get()) {
		var ret string
		return ret
	}
	return *o.MediaKind.Get()
}

// GetMediaKindOk returns a tuple with the MediaKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetMediaKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MediaKind.Get(), o.MediaKind.IsSet()
}

// HasMediaKind returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasMediaKind() bool {
	if o != nil && o.MediaKind.IsSet() {
		return true
	}

	return false
}

// SetMediaKind gets a reference to the given NullableString and assigns it to the MediaKind field.
func (o *MultimodalOperationMetadata) SetMediaKind(v string) {
	o.MediaKind.Set(&v)
}

// SetMediaKindNil sets the value for MediaKind to be an explicit nil
func (o *MultimodalOperationMetadata) SetMediaKindNil() {
	o.MediaKind.Set(nil)
}

// UnsetMediaKind ensures that no value is present for MediaKind, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetMediaKind() {
	o.MediaKind.Unset()
}

// GetPipelineVersion returns the PipelineVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetPipelineVersion() string {
	if o == nil || IsNil(o.PipelineVersion.Get()) {
		var ret string
		return ret
	}
	return *o.PipelineVersion.Get()
}

// GetPipelineVersionOk returns a tuple with the PipelineVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetPipelineVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PipelineVersion.Get(), o.PipelineVersion.IsSet()
}

// HasPipelineVersion returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasPipelineVersion() bool {
	if o != nil && o.PipelineVersion.IsSet() {
		return true
	}

	return false
}

// SetPipelineVersion gets a reference to the given NullableString and assigns it to the PipelineVersion field.
func (o *MultimodalOperationMetadata) SetPipelineVersion(v string) {
	o.PipelineVersion.Set(&v)
}

// SetPipelineVersionNil sets the value for PipelineVersion to be an explicit nil
func (o *MultimodalOperationMetadata) SetPipelineVersionNil() {
	o.PipelineVersion.Set(nil)
}

// UnsetPipelineVersion ensures that no value is present for PipelineVersion, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetPipelineVersion() {
	o.PipelineVersion.Unset()
}

// GetDescriptorModel returns the DescriptorModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetDescriptorModel() string {
	if o == nil || IsNil(o.DescriptorModel.Get()) {
		var ret string
		return ret
	}
	return *o.DescriptorModel.Get()
}

// GetDescriptorModelOk returns a tuple with the DescriptorModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetDescriptorModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DescriptorModel.Get(), o.DescriptorModel.IsSet()
}

// HasDescriptorModel returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasDescriptorModel() bool {
	if o != nil && o.DescriptorModel.IsSet() {
		return true
	}

	return false
}

// SetDescriptorModel gets a reference to the given NullableString and assigns it to the DescriptorModel field.
func (o *MultimodalOperationMetadata) SetDescriptorModel(v string) {
	o.DescriptorModel.Set(&v)
}

// SetDescriptorModelNil sets the value for DescriptorModel to be an explicit nil
func (o *MultimodalOperationMetadata) SetDescriptorModelNil() {
	o.DescriptorModel.Set(nil)
}

// UnsetDescriptorModel ensures that no value is present for DescriptorModel, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetDescriptorModel() {
	o.DescriptorModel.Unset()
}

// GetResolvedModel returns the ResolvedModel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetResolvedModel() string {
	if o == nil || IsNil(o.ResolvedModel.Get()) {
		var ret string
		return ret
	}
	return *o.ResolvedModel.Get()
}

// GetResolvedModelOk returns a tuple with the ResolvedModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetResolvedModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResolvedModel.Get(), o.ResolvedModel.IsSet()
}

// HasResolvedModel returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasResolvedModel() bool {
	if o != nil && o.ResolvedModel.IsSet() {
		return true
	}

	return false
}

// SetResolvedModel gets a reference to the given NullableString and assigns it to the ResolvedModel field.
func (o *MultimodalOperationMetadata) SetResolvedModel(v string) {
	o.ResolvedModel.Set(&v)
}

// SetResolvedModelNil sets the value for ResolvedModel to be an explicit nil
func (o *MultimodalOperationMetadata) SetResolvedModelNil() {
	o.ResolvedModel.Set(nil)
}

// UnsetResolvedModel ensures that no value is present for ResolvedModel, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetResolvedModel() {
	o.ResolvedModel.Unset()
}

// GetStage returns the Stage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetStage() string {
	if o == nil || IsNil(o.Stage.Get()) {
		var ret string
		return ret
	}
	return *o.Stage.Get()
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetStageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stage.Get(), o.Stage.IsSet()
}

// HasStage returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasStage() bool {
	if o != nil && o.Stage.IsSet() {
		return true
	}

	return false
}

// SetStage gets a reference to the given NullableString and assigns it to the Stage field.
func (o *MultimodalOperationMetadata) SetStage(v string) {
	o.Stage.Set(&v)
}

// SetStageNil sets the value for Stage to be an explicit nil
func (o *MultimodalOperationMetadata) SetStageNil() {
	o.Stage.Set(nil)
}

// UnsetStage ensures that no value is present for Stage, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetStage() {
	o.Stage.Unset()
}

// GetChildRetainOperationId returns the ChildRetainOperationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetChildRetainOperationId() string {
	if o == nil || IsNil(o.ChildRetainOperationId.Get()) {
		var ret string
		return ret
	}
	return *o.ChildRetainOperationId.Get()
}

// GetChildRetainOperationIdOk returns a tuple with the ChildRetainOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetChildRetainOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChildRetainOperationId.Get(), o.ChildRetainOperationId.IsSet()
}

// HasChildRetainOperationId returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasChildRetainOperationId() bool {
	if o != nil && o.ChildRetainOperationId.IsSet() {
		return true
	}

	return false
}

// SetChildRetainOperationId gets a reference to the given NullableString and assigns it to the ChildRetainOperationId field.
func (o *MultimodalOperationMetadata) SetChildRetainOperationId(v string) {
	o.ChildRetainOperationId.Set(&v)
}

// SetChildRetainOperationIdNil sets the value for ChildRetainOperationId to be an explicit nil
func (o *MultimodalOperationMetadata) SetChildRetainOperationIdNil() {
	o.ChildRetainOperationId.Set(nil)
}

// UnsetChildRetainOperationId ensures that no value is present for ChildRetainOperationId, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetChildRetainOperationId() {
	o.ChildRetainOperationId.Unset()
}

// GetChildRetainStatus returns the ChildRetainStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetChildRetainStatus() string {
	if o == nil || IsNil(o.ChildRetainStatus.Get()) {
		var ret string
		return ret
	}
	return *o.ChildRetainStatus.Get()
}

// GetChildRetainStatusOk returns a tuple with the ChildRetainStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetChildRetainStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChildRetainStatus.Get(), o.ChildRetainStatus.IsSet()
}

// HasChildRetainStatus returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasChildRetainStatus() bool {
	if o != nil && o.ChildRetainStatus.IsSet() {
		return true
	}

	return false
}

// SetChildRetainStatus gets a reference to the given NullableString and assigns it to the ChildRetainStatus field.
func (o *MultimodalOperationMetadata) SetChildRetainStatus(v string) {
	o.ChildRetainStatus.Set(&v)
}

// SetChildRetainStatusNil sets the value for ChildRetainStatus to be an explicit nil
func (o *MultimodalOperationMetadata) SetChildRetainStatusNil() {
	o.ChildRetainStatus.Set(nil)
}

// UnsetChildRetainStatus ensures that no value is present for ChildRetainStatus, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetChildRetainStatus() {
	o.ChildRetainStatus.Unset()
}

// GetRecallReady returns the RecallReady field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetRecallReady() bool {
	if o == nil || IsNil(o.RecallReady.Get()) {
		var ret bool
		return ret
	}
	return *o.RecallReady.Get()
}

// GetRecallReadyOk returns a tuple with the RecallReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetRecallReadyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecallReady.Get(), o.RecallReady.IsSet()
}

// HasRecallReady returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasRecallReady() bool {
	if o != nil && o.RecallReady.IsSet() {
		return true
	}

	return false
}

// SetRecallReady gets a reference to the given NullableBool and assigns it to the RecallReady field.
func (o *MultimodalOperationMetadata) SetRecallReady(v bool) {
	o.RecallReady.Set(&v)
}

// SetRecallReadyNil sets the value for RecallReady to be an explicit nil
func (o *MultimodalOperationMetadata) SetRecallReadyNil() {
	o.RecallReady.Set(nil)
}

// UnsetRecallReady ensures that no value is present for RecallReady, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetRecallReady() {
	o.RecallReady.Unset()
}

// GetRetryable returns the Retryable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetRetryable() bool {
	if o == nil || IsNil(o.Retryable.Get()) {
		var ret bool
		return ret
	}
	return *o.Retryable.Get()
}

// GetRetryableOk returns a tuple with the Retryable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetRetryableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retryable.Get(), o.Retryable.IsSet()
}

// HasRetryable returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasRetryable() bool {
	if o != nil && o.Retryable.IsSet() {
		return true
	}

	return false
}

// SetRetryable gets a reference to the given NullableBool and assigns it to the Retryable field.
func (o *MultimodalOperationMetadata) SetRetryable(v bool) {
	o.Retryable.Set(&v)
}

// SetRetryableNil sets the value for Retryable to be an explicit nil
func (o *MultimodalOperationMetadata) SetRetryableNil() {
	o.Retryable.Set(nil)
}

// UnsetRetryable ensures that no value is present for Retryable, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetRetryable() {
	o.Retryable.Unset()
}

// GetSanitizedErrorCode returns the SanitizedErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetSanitizedErrorCode() string {
	if o == nil || IsNil(o.SanitizedErrorCode.Get()) {
		var ret string
		return ret
	}
	return *o.SanitizedErrorCode.Get()
}

// GetSanitizedErrorCodeOk returns a tuple with the SanitizedErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetSanitizedErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SanitizedErrorCode.Get(), o.SanitizedErrorCode.IsSet()
}

// HasSanitizedErrorCode returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasSanitizedErrorCode() bool {
	if o != nil && o.SanitizedErrorCode.IsSet() {
		return true
	}

	return false
}

// SetSanitizedErrorCode gets a reference to the given NullableString and assigns it to the SanitizedErrorCode field.
func (o *MultimodalOperationMetadata) SetSanitizedErrorCode(v string) {
	o.SanitizedErrorCode.Set(&v)
}

// SetSanitizedErrorCodeNil sets the value for SanitizedErrorCode to be an explicit nil
func (o *MultimodalOperationMetadata) SetSanitizedErrorCodeNil() {
	o.SanitizedErrorCode.Set(nil)
}

// UnsetSanitizedErrorCode ensures that no value is present for SanitizedErrorCode, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetSanitizedErrorCode() {
	o.SanitizedErrorCode.Unset()
}

// GetProviderRequestId returns the ProviderRequestId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetProviderRequestId() string {
	if o == nil || IsNil(o.ProviderRequestId.Get()) {
		var ret string
		return ret
	}
	return *o.ProviderRequestId.Get()
}

// GetProviderRequestIdOk returns a tuple with the ProviderRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetProviderRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderRequestId.Get(), o.ProviderRequestId.IsSet()
}

// HasProviderRequestId returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasProviderRequestId() bool {
	if o != nil && o.ProviderRequestId.IsSet() {
		return true
	}

	return false
}

// SetProviderRequestId gets a reference to the given NullableString and assigns it to the ProviderRequestId field.
func (o *MultimodalOperationMetadata) SetProviderRequestId(v string) {
	o.ProviderRequestId.Set(&v)
}

// SetProviderRequestIdNil sets the value for ProviderRequestId to be an explicit nil
func (o *MultimodalOperationMetadata) SetProviderRequestIdNil() {
	o.ProviderRequestId.Set(nil)
}

// UnsetProviderRequestId ensures that no value is present for ProviderRequestId, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetProviderRequestId() {
	o.ProviderRequestId.Unset()
}

// GetInputTokens returns the InputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetInputTokens() int64 {
	if o == nil || IsNil(o.InputTokens.Get()) {
		var ret int64
		return ret
	}
	return *o.InputTokens.Get()
}

// GetInputTokensOk returns a tuple with the InputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetInputTokensOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.InputTokens.Get(), o.InputTokens.IsSet()
}

// HasInputTokens returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasInputTokens() bool {
	if o != nil && o.InputTokens.IsSet() {
		return true
	}

	return false
}

// SetInputTokens gets a reference to the given NullableInt64 and assigns it to the InputTokens field.
func (o *MultimodalOperationMetadata) SetInputTokens(v int64) {
	o.InputTokens.Set(&v)
}

// SetInputTokensNil sets the value for InputTokens to be an explicit nil
func (o *MultimodalOperationMetadata) SetInputTokensNil() {
	o.InputTokens.Set(nil)
}

// UnsetInputTokens ensures that no value is present for InputTokens, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetInputTokens() {
	o.InputTokens.Unset()
}

// GetOutputTokens returns the OutputTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetOutputTokens() int64 {
	if o == nil || IsNil(o.OutputTokens.Get()) {
		var ret int64
		return ret
	}
	return *o.OutputTokens.Get()
}

// GetOutputTokensOk returns a tuple with the OutputTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetOutputTokensOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OutputTokens.Get(), o.OutputTokens.IsSet()
}

// HasOutputTokens returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasOutputTokens() bool {
	if o != nil && o.OutputTokens.IsSet() {
		return true
	}

	return false
}

// SetOutputTokens gets a reference to the given NullableInt64 and assigns it to the OutputTokens field.
func (o *MultimodalOperationMetadata) SetOutputTokens(v int64) {
	o.OutputTokens.Set(&v)
}

// SetOutputTokensNil sets the value for OutputTokens to be an explicit nil
func (o *MultimodalOperationMetadata) SetOutputTokensNil() {
	o.OutputTokens.Set(nil)
}

// UnsetOutputTokens ensures that no value is present for OutputTokens, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetOutputTokens() {
	o.OutputTokens.Unset()
}

// GetLogicalCalls returns the LogicalCalls field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetLogicalCalls() int64 {
	if o == nil || IsNil(o.LogicalCalls.Get()) {
		var ret int64
		return ret
	}
	return *o.LogicalCalls.Get()
}

// GetLogicalCallsOk returns a tuple with the LogicalCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetLogicalCallsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.LogicalCalls.Get(), o.LogicalCalls.IsSet()
}

// HasLogicalCalls returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasLogicalCalls() bool {
	if o != nil && o.LogicalCalls.IsSet() {
		return true
	}

	return false
}

// SetLogicalCalls gets a reference to the given NullableInt64 and assigns it to the LogicalCalls field.
func (o *MultimodalOperationMetadata) SetLogicalCalls(v int64) {
	o.LogicalCalls.Set(&v)
}

// SetLogicalCallsNil sets the value for LogicalCalls to be an explicit nil
func (o *MultimodalOperationMetadata) SetLogicalCallsNil() {
	o.LogicalCalls.Set(nil)
}

// UnsetLogicalCalls ensures that no value is present for LogicalCalls, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetLogicalCalls() {
	o.LogicalCalls.Unset()
}

// GetPhysicalAttempts returns the PhysicalAttempts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetPhysicalAttempts() int64 {
	if o == nil || IsNil(o.PhysicalAttempts.Get()) {
		var ret int64
		return ret
	}
	return *o.PhysicalAttempts.Get()
}

// GetPhysicalAttemptsOk returns a tuple with the PhysicalAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetPhysicalAttemptsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhysicalAttempts.Get(), o.PhysicalAttempts.IsSet()
}

// HasPhysicalAttempts returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasPhysicalAttempts() bool {
	if o != nil && o.PhysicalAttempts.IsSet() {
		return true
	}

	return false
}

// SetPhysicalAttempts gets a reference to the given NullableInt64 and assigns it to the PhysicalAttempts field.
func (o *MultimodalOperationMetadata) SetPhysicalAttempts(v int64) {
	o.PhysicalAttempts.Set(&v)
}

// SetPhysicalAttemptsNil sets the value for PhysicalAttempts to be an explicit nil
func (o *MultimodalOperationMetadata) SetPhysicalAttemptsNil() {
	o.PhysicalAttempts.Set(nil)
}

// UnsetPhysicalAttempts ensures that no value is present for PhysicalAttempts, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetPhysicalAttempts() {
	o.PhysicalAttempts.Unset()
}

// GetPossibleDuplicateProviderAttempt returns the PossibleDuplicateProviderAttempt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MultimodalOperationMetadata) GetPossibleDuplicateProviderAttempt() bool {
	if o == nil || IsNil(o.PossibleDuplicateProviderAttempt.Get()) {
		var ret bool
		return ret
	}
	return *o.PossibleDuplicateProviderAttempt.Get()
}

// GetPossibleDuplicateProviderAttemptOk returns a tuple with the PossibleDuplicateProviderAttempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MultimodalOperationMetadata) GetPossibleDuplicateProviderAttemptOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.PossibleDuplicateProviderAttempt.Get(), o.PossibleDuplicateProviderAttempt.IsSet()
}

// HasPossibleDuplicateProviderAttempt returns a boolean if a field has been set.
func (o *MultimodalOperationMetadata) HasPossibleDuplicateProviderAttempt() bool {
	if o != nil && o.PossibleDuplicateProviderAttempt.IsSet() {
		return true
	}

	return false
}

// SetPossibleDuplicateProviderAttempt gets a reference to the given NullableBool and assigns it to the PossibleDuplicateProviderAttempt field.
func (o *MultimodalOperationMetadata) SetPossibleDuplicateProviderAttempt(v bool) {
	o.PossibleDuplicateProviderAttempt.Set(&v)
}

// SetPossibleDuplicateProviderAttemptNil sets the value for PossibleDuplicateProviderAttempt to be an explicit nil
func (o *MultimodalOperationMetadata) SetPossibleDuplicateProviderAttemptNil() {
	o.PossibleDuplicateProviderAttempt.Set(nil)
}

// UnsetPossibleDuplicateProviderAttempt ensures that no value is present for PossibleDuplicateProviderAttempt, not even an explicit nil
func (o *MultimodalOperationMetadata) UnsetPossibleDuplicateProviderAttempt() {
	o.PossibleDuplicateProviderAttempt.Unset()
}

func (o MultimodalOperationMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultimodalOperationMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AssetId.IsSet() {
		toSerialize["asset_id"] = o.AssetId.Get()
	}
	if o.AssetSha256.IsSet() {
		toSerialize["asset_sha256"] = o.AssetSha256.Get()
	}
	if o.MediaKind.IsSet() {
		toSerialize["media_kind"] = o.MediaKind.Get()
	}
	if o.PipelineVersion.IsSet() {
		toSerialize["pipeline_version"] = o.PipelineVersion.Get()
	}
	if o.DescriptorModel.IsSet() {
		toSerialize["descriptor_model"] = o.DescriptorModel.Get()
	}
	if o.ResolvedModel.IsSet() {
		toSerialize["resolved_model"] = o.ResolvedModel.Get()
	}
	if o.Stage.IsSet() {
		toSerialize["stage"] = o.Stage.Get()
	}
	if o.ChildRetainOperationId.IsSet() {
		toSerialize["child_retain_operation_id"] = o.ChildRetainOperationId.Get()
	}
	if o.ChildRetainStatus.IsSet() {
		toSerialize["child_retain_status"] = o.ChildRetainStatus.Get()
	}
	if o.RecallReady.IsSet() {
		toSerialize["recall_ready"] = o.RecallReady.Get()
	}
	if o.Retryable.IsSet() {
		toSerialize["retryable"] = o.Retryable.Get()
	}
	if o.SanitizedErrorCode.IsSet() {
		toSerialize["sanitized_error_code"] = o.SanitizedErrorCode.Get()
	}
	if o.ProviderRequestId.IsSet() {
		toSerialize["provider_request_id"] = o.ProviderRequestId.Get()
	}
	if o.InputTokens.IsSet() {
		toSerialize["input_tokens"] = o.InputTokens.Get()
	}
	if o.OutputTokens.IsSet() {
		toSerialize["output_tokens"] = o.OutputTokens.Get()
	}
	if o.LogicalCalls.IsSet() {
		toSerialize["logical_calls"] = o.LogicalCalls.Get()
	}
	if o.PhysicalAttempts.IsSet() {
		toSerialize["physical_attempts"] = o.PhysicalAttempts.Get()
	}
	if o.PossibleDuplicateProviderAttempt.IsSet() {
		toSerialize["possible_duplicate_provider_attempt"] = o.PossibleDuplicateProviderAttempt.Get()
	}
	return toSerialize, nil
}

type NullableMultimodalOperationMetadata struct {
	value *MultimodalOperationMetadata
	isSet bool
}

func (v NullableMultimodalOperationMetadata) Get() *MultimodalOperationMetadata {
	return v.value
}

func (v *NullableMultimodalOperationMetadata) Set(val *MultimodalOperationMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableMultimodalOperationMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableMultimodalOperationMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultimodalOperationMetadata(val *MultimodalOperationMetadata) *NullableMultimodalOperationMetadata {
	return &NullableMultimodalOperationMetadata{value: val, isSet: true}
}

func (v NullableMultimodalOperationMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultimodalOperationMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
