# coding: utf-8

"""
    HMS HTTP API

    HTTP API for HMS

    The version of the OpenAPI document: 0.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class MultimodalOperationMetadata(BaseModel):
    """
    Stable, payload-free status for a multimodal file-retain operation.
    """ # noqa: E501
    asset_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=4096)]] = None
    asset_sha256: Optional[Annotated[str, Field(strict=True)]] = None
    media_kind: Optional[StrictStr] = None
    pipeline_version: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]] = None
    descriptor_model: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]] = None
    resolved_model: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=256)]] = None
    stage: Optional[StrictStr] = None
    child_retain_operation_id: Optional[Annotated[str, Field(strict=True)]] = None
    child_retain_status: Optional[StrictStr] = None
    recall_ready: Optional[StrictBool] = None
    retryable: Optional[StrictBool] = None
    sanitized_error_code: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    provider_request_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=512)]] = None
    input_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    output_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    logical_calls: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    physical_attempts: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    possible_duplicate_provider_attempt: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["asset_id", "asset_sha256", "media_kind", "pipeline_version", "descriptor_model", "resolved_model", "stage", "child_retain_operation_id", "child_retain_status", "recall_ready", "retryable", "sanitized_error_code", "provider_request_id", "input_tokens", "output_tokens", "logical_calls", "physical_attempts", "possible_duplicate_provider_attempt"]

    @field_validator('asset_sha256')
    def asset_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{64}$/")
        return value

    @field_validator('media_kind')
    def media_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['image', 'video']):
            raise ValueError("must be one of enum values ('image', 'video')")
        return value

    @field_validator('stage')
    def stage_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['received', 'stored', 'validated', 'preprocessed', 'describing', 'normalized', 'retain_queued', 'retain_failed', 'recall_ready', 'failed']):
            raise ValueError("must be one of enum values ('received', 'stored', 'validated', 'preprocessed', 'describing', 'normalized', 'retain_queued', 'retain_failed', 'recall_ready', 'failed')")
        return value

    @field_validator('child_retain_operation_id')
    def child_retain_operation_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/")
        return value

    @field_validator('child_retain_status')
    def child_retain_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'processing', 'completed', 'failed', 'cancelled', 'not_found']):
            raise ValueError("must be one of enum values ('pending', 'processing', 'completed', 'failed', 'cancelled', 'not_found')")
        return value

    @field_validator('sanitized_error_code')
    def sanitized_error_code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9]+(?:[._-][a-z0-9]+)*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MultimodalOperationMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if asset_id (nullable) is None
        # and model_fields_set contains the field
        if self.asset_id is None and "asset_id" in self.model_fields_set:
            _dict['asset_id'] = None

        # set to None if asset_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.asset_sha256 is None and "asset_sha256" in self.model_fields_set:
            _dict['asset_sha256'] = None

        # set to None if media_kind (nullable) is None
        # and model_fields_set contains the field
        if self.media_kind is None and "media_kind" in self.model_fields_set:
            _dict['media_kind'] = None

        # set to None if pipeline_version (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_version is None and "pipeline_version" in self.model_fields_set:
            _dict['pipeline_version'] = None

        # set to None if descriptor_model (nullable) is None
        # and model_fields_set contains the field
        if self.descriptor_model is None and "descriptor_model" in self.model_fields_set:
            _dict['descriptor_model'] = None

        # set to None if resolved_model (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_model is None and "resolved_model" in self.model_fields_set:
            _dict['resolved_model'] = None

        # set to None if stage (nullable) is None
        # and model_fields_set contains the field
        if self.stage is None and "stage" in self.model_fields_set:
            _dict['stage'] = None

        # set to None if child_retain_operation_id (nullable) is None
        # and model_fields_set contains the field
        if self.child_retain_operation_id is None and "child_retain_operation_id" in self.model_fields_set:
            _dict['child_retain_operation_id'] = None

        # set to None if child_retain_status (nullable) is None
        # and model_fields_set contains the field
        if self.child_retain_status is None and "child_retain_status" in self.model_fields_set:
            _dict['child_retain_status'] = None

        # set to None if recall_ready (nullable) is None
        # and model_fields_set contains the field
        if self.recall_ready is None and "recall_ready" in self.model_fields_set:
            _dict['recall_ready'] = None

        # set to None if retryable (nullable) is None
        # and model_fields_set contains the field
        if self.retryable is None and "retryable" in self.model_fields_set:
            _dict['retryable'] = None

        # set to None if sanitized_error_code (nullable) is None
        # and model_fields_set contains the field
        if self.sanitized_error_code is None and "sanitized_error_code" in self.model_fields_set:
            _dict['sanitized_error_code'] = None

        # set to None if provider_request_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_request_id is None and "provider_request_id" in self.model_fields_set:
            _dict['provider_request_id'] = None

        # set to None if input_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.input_tokens is None and "input_tokens" in self.model_fields_set:
            _dict['input_tokens'] = None

        # set to None if output_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.output_tokens is None and "output_tokens" in self.model_fields_set:
            _dict['output_tokens'] = None

        # set to None if logical_calls (nullable) is None
        # and model_fields_set contains the field
        if self.logical_calls is None and "logical_calls" in self.model_fields_set:
            _dict['logical_calls'] = None

        # set to None if physical_attempts (nullable) is None
        # and model_fields_set contains the field
        if self.physical_attempts is None and "physical_attempts" in self.model_fields_set:
            _dict['physical_attempts'] = None

        # set to None if possible_duplicate_provider_attempt (nullable) is None
        # and model_fields_set contains the field
        if self.possible_duplicate_provider_attempt is None and "possible_duplicate_provider_attempt" in self.model_fields_set:
            _dict['possible_duplicate_provider_attempt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MultimodalOperationMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asset_id": obj.get("asset_id"),
            "asset_sha256": obj.get("asset_sha256"),
            "media_kind": obj.get("media_kind"),
            "pipeline_version": obj.get("pipeline_version"),
            "descriptor_model": obj.get("descriptor_model"),
            "resolved_model": obj.get("resolved_model"),
            "stage": obj.get("stage"),
            "child_retain_operation_id": obj.get("child_retain_operation_id"),
            "child_retain_status": obj.get("child_retain_status"),
            "recall_ready": obj.get("recall_ready"),
            "retryable": obj.get("retryable"),
            "sanitized_error_code": obj.get("sanitized_error_code"),
            "provider_request_id": obj.get("provider_request_id"),
            "input_tokens": obj.get("input_tokens"),
            "output_tokens": obj.get("output_tokens"),
            "logical_calls": obj.get("logical_calls"),
            "physical_attempts": obj.get("physical_attempts"),
            "possible_duplicate_provider_attempt": obj.get("possible_duplicate_provider_attempt")
        })
        return _obj
